package:
  name: quantlib
  version: 1.3

source:
  git_url: https://github.com/lballabio/QuantLib.git
  git_tag: QuantLib-v1.3

build:
  number : 1 
  rpaths:
    - /mass/app/gcc/4.8.2_64/lib64

requirements:
  build:
    - boost
  run:
    - boost

about:
  home: http://quantlib.org
  license: New BSD
