package:
  name: keras
  version: 0.3.0

source:
  git_url: https://github.com/fchollet/keras.git
  git_tag: 0.3.0

requirements:
  build:
    - python
    - six
    - pyyaml
    - numpy
    - scipy
    - hdf5
    - theano

  run:
    - python

about:
  home: http://keras.io
  license: MIT
